version: v1.64.0

destination: ./testdata/src

plugins:
  # a plugin from a Go proxy
#  - module: 'github.com/AdamBrianBright/errstack'
#    import: 'github.com/AdamBrianBright/errstack/cmd/gclplugin'
#    version: v0.2.0

  # a plugin from local source
  - module: 'github.com/AdamBrianBright/errstack'
    import: 'github.com/AdamBrianBright/errstack/cmd/gclplugin'
    path: .
