# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: 3

env:
  GOTOOLCHAIN: go1.23.12

tasks:
  build:
    cmd: go build -v -o ./build/errstack -ldflags "-s -w" ./cmd/errstack
  test:
    cmds:
      - go test -v -count=1 -cpuprofile=cpu.prof -memprofile=mem.prof -benchmem -bench=. .
  lint:
    cmd: golangci-lint run ./...
  fmt:
    cmd: go fmt ./...
  tidy:
    cmd: go mod tidy
  clean:
    silent: true
    cmd: rm -rf bin cpu.prof mem.prof errstack.test errstack.log
  install/lint:
    cmd: go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
  install/self:
    cmd: go install ./cmd/errstack
  install/custom-gcl:
    cmd: golangci-lint custom
    sources: [ ./**/*.go ]
    generates: [ ./testdata/src/custom-gcl ]
  run:
    cmds:
      - ./custom-gcl cache clean
      #      - ./custom-gcl run ./return_mixed_numbers/...
      - ./custom-gcl run ./rewritten_error/...
    dir: testdata/src
    deps: [ install/custom-gcl ]
